### ISSUE TITLE
Update Alpine Linux to 3.10.3

### ISSUE THREAD

**Issue by sanmai-NL** [pblaas/docker_openstack-cli#1]
Besides security fixes, it provides a newer `curl` package that supports parallel downloads.

**Comment by pblaas** [comment]
Thanks for the pointer, will update the dockerfile.

**Comment by pblaas** [comment]
updated with https://github.com/pblaas/docker_openstack-cli/commit/9addb72e1f7b665729c6707b08b8783ce84baaf6.
